window.App = Ember.Application.create()

require('Mixins.js')
require('Components.js')
require('Controllers.js')
require('Models.js')
require('Fixtures.js')
require('Router.js')
require('Store.js')
require('Utils.js')
